Executable = dummy.sh
use_x509userproxy = true
Log        = jobs/log_running_$(ProcId)_All.log
Output     = jobs/log_running_$(ProcId)_All.out
Error      = jobs/log_running_$(ProcId)_All.error
+JobFlavour = "workday"
getenv = True
MY.SingularityImage = "/cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-cat/cmssw-lxplus/cmssw-el7-lxplus:latest/"
+AccountingGroup = "group_u_CMST3.all"
arguments  = $(info)
queue info from (
2016APV TBar_tWch_noFullyHad
2016APV TBar_tch
2016APV TTSemi_pow_part0
2016APV TTSemi_pow_part1
2016APV WJetsToLNu_Pt100To250_part0
2016APV WJetsToLNu_Pt100To250_part1
2016APV WJetsToLNu_Pt250To400_part2
2016APV WJetsToLNu_Pt250To400_part3
)