Executable = dummy.sh
use_x509userproxy = true
Log        = jobs/log_running_$(ProcId)_All.log
Output     = jobs/log_running_$(ProcId)_All.out
Error      = jobs/log_running_$(ProcId)_All.error
+JobFlavour = "longlunch"
getenv = True
MY.SingularityImage = "/cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/cms-cat/cmssw-lxplus/cmssw-el7-lxplus:latest/"
+AccountingGroup = "group_u_CMST3.all"
arguments  = $(info)
queue info from (
2017  SingleMuon_Run2017C_GT_UL2017_part1 1 
2017  SingleMuon_Run2017E_GT_UL2017_part0 6
2017  SingleMuon_Run2017E_GT_UL2017_part0 7
2017  SingleMuon_Run2017E_GT_UL2017_part0 11
2017  SingleMuon_Run2017E_GT_UL2017_part0 13
2017  SingleMuon_Run2017F_GT_UL2017_part0 6
2017  SingleMuon_Run2017F_GT_UL2017_part0 7
2017  SingleMuon_Run2017F_GT_UL2017_part0 8
2017  SingleMuon_Run2017F_GT_UL2017_part0 12
2017  SingleMuon_Run2017C_GT_UL2017_part0 3
2017  SingleMuon_Run2017C_GT_UL2017_part0 4
2017  SingleMuon_Run2017C_GT_UL2017_part0 10
2017  SingleMuon_Run2017C_GT_UL2017_part0 13
2017  SingleMuon_Run2017C_GT_UL2017_part0 19
2017  SingleMuon_Run2017B_GT_UL2017 1
)
