##### BEGIN condor submit file
Executable = lxbatch_runner.sh
Error      = /afs/cern.ch/work/a/anmehta/public/dpsww_runII/CMSSW_10_2_16_UL/src/CMGTools/DPSWW/macros/logs/err.$(cluster).$(Dataset).$(Step)
Output     = /afs/cern.ch/work/a/anmehta/public/dpsww_runII/CMSSW_10_2_16_UL/src/CMGTools/DPSWW/macros/logs/out.$(cluster).$(Dataset).$(Step)
Log        = /afs/cern.ch/work/a/anmehta/public/dpsww_runII/CMSSW_10_2_16_UL/src/CMGTools/DPSWW/macros/logs/log.$(cluster).$(Dataset).$(Step)

use_x509userproxy = True
getenv = True
request_memory = 2000
+MaxRuntime = 6000


Arguments = /afs/cern.ch/work/a/anmehta/public/dpsww_runII/CMSSW_10_2_16_UL/src/CMGTools/DPSWW/macros /afs/cern.ch/work/a/anmehta/public/dpsww_runII/CMSSW_10_2_16_UL python prepareEventVariablesFriendTree.py -j 0 -N 500000  -t NanoAOD /eos/cms/store/cmst3/group/dpsww/Aut18nanoaodV7/ /eos/cms/store/cmst3/group/dpsww/Aut18nanoaodV7//postFSRinfo/  -I  CMGTools.DPSWW.tools.nanoAOD.ttH_modules genInfo_py8_fur_taus  --compression ZLIB:3  -d $(Dataset) -c $(Step)

Queue 2 Dataset in WWDoubleTo2L_newsim
Queue 2 Dataset in WWTo2L2Nu_DoubleScattering_13TeV-pythia8
Queue 2 Dataset in WW_DoubleScattering_13TeV-pythia8_TuneCP5
