##### BEGIN condor submit file
Executable = lxbatch_runner.sh
Universe   = vanilla
Error      = /afs/cern.ch/work/a/anmehta/public/dpsww_runII/CMSSW_10_2_16_UL/src/CMGTools/DPSWW/macros/logs/err.$(cluster).$(Dataset).$(Step)
Output     = /afs/cern.ch/work/a/anmehta/public/dpsww_runII/CMSSW_10_2_16_UL/src/CMGTools/DPSWW/macros/logs/out.$(cluster).$(Dataset).$(Step)
Log        = /afs/cern.ch/work/a/anmehta/public/dpsww_runII/CMSSW_10_2_16_UL/src/CMGTools/DPSWW/macros/logs/log.$(cluster).$(Dataset).$(Step)

use_x509userproxy = True
getenv = True
request_memory = 2000
+MaxRuntime = 10800


Arguments = /afs/cern.ch/work/a/anmehta/public/dpsww_runII/CMSSW_10_2_16_UL/src/CMGTools/DPSWW/macros /afs/cern.ch/work/a/anmehta/public/dpsww_runII/CMSSW_10_2_16_UL python prepareEventVariablesFriendTree.py -j 0 -N 10000  -t NanoAOD /eos/cms/store/cmst3/group/dpsww/NanoTrees_v7_dpsww_04092020/2018/ /eos/cms/store/cmst3/group/dpsww/NanoTrees_v7_dpsww_04092020/2018/2_recl/  -I  CMGTools.DPSWW.tools.nanoAOD.ttH_modules recleaner_step1,recleaner_step2_mc,mcMatch_seq,higgsDecay,triggerSequence  --compression ZLIB:3  -d $(Dataset) -c $(Step)

Queue 6 Dataset in W4JetsToLNu_LO
